# Usefull alias
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias f='find -name'
alias du='du -d 1 -h'
alias df='df -h'
alias bpython='python -m bpython'
alias na='nautilus'

# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Pass options to free ##
alias meminfo='free -m -l -t -h'

# Get server cpu info ##
alias cpuinfo='lscpu'

# Padtec usefull alias ##
alias tb='topbuild'
alias tbb='topbuild build'
alias tbc='topbuild clean'
alias tbi='topbuild install'
alias tbf='topbuild fetch'
alias tbt='topbuild toolchain'
alias wkb='padinstall build'
alias wki='padinstall install'
alias wkp='padinstall installproj'
alias wkc='padinstall clearall'
alias wkcp='padinstall copy --cp'
alias wkssh='padinstall fixssh'
alias padgrep='grep --exclude-dir={build,cmake,topbuild} --exclude={.*txt} -RI'
#alias cdp='cd <path to the working project>'

